-- INSERT INTO stories(id, title, content, completed, users_id)
-- -- Uncompleted Stories
--   VALUES (1, 'Harmonic Dust', 'The parched earth groaned under a relentless sun, the horizon shimmering like a mirage above the cracked and dusty plains.
--   A lone rider, silhouetted against the dying embers of the day, cut a lonely figure.
--   His weathered Stetson sat low over eyes that held the weariness of a thousand sun-baked miles,
--   his chapped lips pursed around a harmonica that whined a mournful tune of lost hopes and empty promises.
--   This was no Sunday stroll through fields of sunflowers; this was a man riding into the teeth of a dust storm,
--   a storm brewing not just in the sky, but in the depths of his soul.', FALSE, 1),
-- (2, 'Through the Skylight', 'Rain pummeled the corrugated metal roof of the gym, drumming a chaotic rhythm against the echoes of squeaking sneakers and grunts of exertion.
--   Maya dribbled with steely focus, the worn orange basketball an extension of her pulse, weaving through a gauntlet of towering shadows in crimson jerseys.
--   Beads of sweat stung her eyes, blending with the rain that leaked through the skylights, turning the court into a slick battlefield.
--   Today, the state championship wasnt just a trophy; it was her escape ticket,
--   a one-way pass out of this dead-end town and into a future as bright and boundless as the sky before the storm.
--   Her heart pounded, a counterpoint to the rains relentless roar, each beat a promise and a prayer – this dribble, this pass, this shot,
--   anything to break free from the gravity of her small-town dreams.', FALSE, 1),
-- (3, 'Whinnying for Wings', 'The sun, a giant orange yolk smeared across the stable ceiling, oozed its morning light onto Buttercup.
--   She stretched, hooves tucked like dainty ballet slippers beneath her chest, and squinted at the dust motes dancing in the golden beam.
--   But the joy of a new day, the usual thrum of anticipation for oats and playful nudges from her stablemate, Prince Charming, remained stubbornly absent.
--   Instead, a gnawing pang, as familiar as the hay she chomped and as old as the cobwebs in the rafters, settled in her chest.
--   "Why, oh why," she sighed, the breath ruffling her chestnut mane, "cant I just be a duck?" The thought had plagued her since she first wobbled on spindly legs,
--   a foal yearning for the boundless sky, not the four-walled horizon of the stable. Today,
--   with the sun whispering of open horizons and a pond shimmering below the barn window, the ache was especially acute.
--   She longed to trade her hay for pondweed, her hooves for webbed feet, her whinny for a cheery quack.
--   Maybe, just maybe, this could be the day she finally took flight, no wings needed, just pure, feathery desire and a pond full of possibilities.', FALSE, 2),
-- (4, 'Quantum Alphabet Soup', 'A crackle of static birthed a neon butterfly from the television screen, its wings morphing into tangled constellations before melting into a puddle of pixels.
--   Across the room, a book coughed dust as its spine unfurled, pages whispering incantations in tongues of swirling ink.
--   Sunlight filtering through a prismatic chandelier shattered, casting rainbows onto a bowl of alphabet soup where letters writhed and morphed,
--   forming fleeting sentences before dissolving back into broth. In this apartment, reality was a kaleidoscope, each fragment fracturing further,
--   an endless dance of meaning unmoored from form. And nestled amongst the chaos, sat Alice, eyes wide and curious,
--   ready to tumble down the rabbit hole into a labyrinth of her own making.', FALSE, 2),
--   -- Completed stories
-- (5, 'Duck-Duck, The Duck', 'Duck-Duck, the Duck, wasn''t like the other ducks. While his buddies bobbed merrily on the pond, quacking away about worms and puddles,
--   Duck-Duck dreamed of loftier things. He yearned to dance on clouds, sing with the stars, and fly beyond the horizon.
--   Every morning, as the sun painted the sky with gentle orange and pink, Duck-Duck would flap his tiny wings as hard as he could,
--   hoping to catch a breeze and lift him into the air. But all he managed was a hilarious, duck-bottomed shuffle across the water,
--   sending ripples bouncing and his siblings into fits of giggles.
--   One day, a wise old goose with feathers like fluffy snow saw Duck-Duck''s persistent flapping. "Little one," he honked kindly,
--   "you can''t fly with ordinary wings. You need wings of dreams, woven from moonlight and wishes."
--   Intrigued, Duck-Duck spent that night gazing at the moon, whispering his greatest dreams into the cool night air.
--   As the first rays of dawn kissed the water, he felt a strange fluttering in his chest. He looked down and gasped.
--   There, nestled against his heart, were two shimmering wings, like spun moonlight and stardust!
--   With a joyous quack, Duck-Duck unfurled his wings and took to the sky. He danced with the clouds, sang with the stars,
--   and soared beyond the horizon, his dreams finally taking flight. And though he always returned to the pond,
--   sharing stories of his adventures with his siblings, Duck-Duck, the Duck, never forgot the wise goose''s words:
--   the most beautiful wings are the ones woven from dreams.', TRUE, 1),
-- (6, 'Concrete Jungles and Manicured Lawns: A Streetwise Prince in Bel-Air', '
--   West Philadelphia, born and raised. That''s where I spent most of my days, chillin'' out, maxin'', relaxin'' all cool.
--   My name''s Lil'' Jazzy, streetwise and smooth, but my life wasn''t all sunshine and parkway jams. My pops, bless his soul,
--   got caught in a jam, a bad one, the kind with sirens and orange jumpsuits. So it was Uncle Phil, big and rich, who stepped in,
--   whisking me away from the concrete jungle to the gated paradise of Bel-Air.
--   Now, Bel-Air ain''t Philly. It''s mansions and manicured lawns, fancy cars and caviar breakfasts.
--   My cousins, Carlton and Hilary, were like polished ponies, all rules and etiquette, while I was a dust bunny,
--   tracking grime across their white carpets. We clashed like cymbals and a kazoo, me with my slang and street smarts,
--   them with their stuffy manners and opera nights. But hey, opposites attract, right? We learned from each other,
--   Carlton loosening up a bit, me learning to hold a fork without stabbing the tablecloth.
--   Bel-Air wasn''t Philly, but it became my home. I learned to play polo on the polo field, mastered the art of the perfect topiary trim,
--   and even impressed Aunt Vivian with my freestyle rap skills at her charity gala. Sure, there were bumps along the way,
--   culture clashes and misunderstandings, but we were a family, a motley crew of misfits who found harmony in the most unexpected places.
--   And maybe, just maybe, this fresh prince of Bel-Air had found his kingdom, not in a swanky mansion,
--   but in the hearts of the people who filled it with laughter, love, and the occasional rap battle.
--   In the end, it wasn''t about the fancy cars or the caviar breakfasts. It was about finding your place, your tribe,
--   your own version of Bel-Air. And somewhere, between the manicured lawns and the concrete jungle, I found mine.', TRUE, 1),
-- (7, 'The Case of the Crumb Caper: One Duck Detective''s Quacking Adventure', 'Beatrice Beefeater, duck detective extraordinaire, wasn''t your average puddle pouncer.
--   While her flock waddled about, blissfully unaware of the pond''s underbelly of fishy secrets,
--   Beatrice yearned for a life of trenchcoats (well, repurposed tea cozies) and magnifying glasses
--   (fashioned from a discarded contact lens). Her dreams were filled with shadowy figures, stolen worms,
--   and quacking pronouncements of "The case is cracked!"
--   One sunny afternoon, a frantic mallard waddled up, beak trembling. His precious stash of breadcrumbs,
--   meticulously collected from discarded sandwiches, had vanished! Beatrice, her ducky antennae twitching with intrigue,
--   donned her tea cozy trenchcoat and grabbed her contact lens monocle. "Fear not, fowl friend," she declared,
--   puffing out her chest (which mostly just ruffled her feathers). "Beatrice Beefeater is on the case!"
--   Her investigation was, well, unique. She interrogated grumpy catfish,
--   who mumbled through gulps of algae about suspicious bread crumbs floating suspiciously by their lair.
--   She followed a trail of crumbs (which ended abruptly in a hungry duckling''s belly) and examined footprints
--   (mostly just webbed imprints leading in every direction).
--   Finally, Beatrice stubbed her foot (again) on a discarded baguette crust. Underneath, a beady eye peered out.
--   It was Humphrey, the pond bully, notorious for his insatiable appetite and questionable table manners.
--   He confessed to the breadcrumb heist, pleading temporary insanity brought on by too much pond scum.
--   Beatrice, magnanimous even in the face of stolen snacks, declared the case closed.
--   Humphrey, in a rare moment of generosity, offered Beatrice a particularly juicy worm as a reward.
--   As she savored her detective''s fee, Beatrice couldn''t help but think, maybe duck detective wasn''t
--   all glamorous trenchcoats and dramatic reveals. But then again, who could resist a hero who solved crimes
--   with a contact lens monocle and a penchant for tripping over crusty bread? In the wacky world of the pond,
--   Beatrice Beefeater, the clumsiest, most breadcrumb-obsessed detective around, was just the duck for the job.', TRUE, 3);
INSERT INTO stories(id, title, content, completed, users_id)
  VALUES (1, 'Adventure Awaits', 'Embark on an exhilarating journey through uncharted lands, where the unknown beckons with the promise of discovery. With each step, the landscape unfolds, revealing the mysteries that lie hidden beyond the familiar horizon. This expedition is a testament to the spirit of exploration, inviting you to traverse unexplored terrain and embrace the thrill of venturing into the limitless possibilities that await on this uncharted path.', TRUE, 1),
(2, 'Mystery of the Missing Artifact', 'A captivating quest where the challenge unfolds: solve the puzzle to reveal the elusive ancient artifact. This cerebral adventure demands keen intellect and unwavering determination. Each puzzle piece is a key, unlocking the gates to a forgotten era, where the relic''s significance lies veiled in history''s shadows. The intricate tapestry of riddles, echoing ancient wisdom, tests the boundaries of logic and intuition. Success promises a connection with the legacy of a bygone era, making this enigmatic journey a thrilling odyssey into the depths of mystery and historical intrigue.', FALSE, 2),
(3, 'The Silent Forest', 'Delve into the eerie silence of a mysterious forest, where shadows dance among ancient trees. Explore the unknown as you navigate through the quiet expanse, feeling the weight of secrets held within the stillness. This journey beckons, inviting you to unravel the enigma concealed in the haunting tranquility of the woodland realm.', TRUE, 3),
(4, 'City of Dreams', 'A tale of ambition and challenges set against the backdrop of a bustling city. Here, aspirations soar amid the towering skyscrapers as individuals navigate the labyrinth of opportunities and obstacles. The urban landscape becomes a canvas for dreams, each step resonating with the pulse of ambition. Yet, amidst the ceaseless rhythm of progress, challenges loom, testing resilience and determination. The city becomes both mentor and adversary, shaping destinies in its dynamic embrace. Through the ebb and flow of daily life, characters grapple with ambition''s triumphs and tribulations, unraveling a narrative that mirrors the multifaceted essence of pursuing dreams in the vibrant, unforgiving heart of urban existence.', FALSE, 4),
(5, 'Beyond the Stars', 'In the cosmic odyssey that unfolds, explore the secrets veiled within the vastness of space. Venture into uncharted territories, where the celestial tapestry conceals mysteries waiting to be unraveled. Amidst distant galaxies and enigmatic phenomena, the journey beckons, promising a captivating narrative. As the protagonist of this cosmic tale, immerse yourself in the quest to unveil the hidden truths that shape the wonders of the universe, and let the story of discovery unfold amidst the stars.', FALSE, 5),
(6, 'Lost in Time', 'Awakening in a temporal abyss, Alex found themselves displaced across epochs. Stranded in a kaleidoscope of eras, the quest to find a way back home became an enigmatic odyssey. From the grandeur of ancient civilizations to the gleaming possibilities of the future, each era presented a unique challenge. As the time-traveler navigated through the tapestry of history, they grappled with unforeseen perils and discovered the profound secrets hidden within the folds of time, all in pursuit of the elusive path leading back to familiar grounds.', FALSE, 6),
(7, 'Whispers in the Dark', 'In the dimly lit corridors of an old mansion, Amelia received an ancient key, unlocking a world veiled in mystery. As she delved into the shadows, a hidden tapestry of secrets began to unravel. The air thickened with anticipation, and the journey into the enigmatic depths of the unknown beckoned, casting shadows of intrigue across her path.', TRUE, 7),
(8, 'The Enchanted Garden', 'Amelia stumbled upon a forgotten gate nestled in a meadow, opening to a magical garden pulsating with vibrant hues and enchanting melodies. As she stepped into this realm, mystical creatures danced amid blooming wonders. The air resonated with magic, inviting Amelia to unravel the secrets hidden within this fantastical haven, where every flower whispered tales of ancient enchantments.', FALSE, 8),
(9, 'Echoes of the Past', 'In the hushed corridors of an ancient library, a timeworn map materialized, whispering of untold treasures. Intrigued, Clara embarked on a journey where echoes of history guided her steps. Navigating through forgotten realms, she unearthed hidden artifacts and stories buried in time. Each discovery echoed the secrets of the past, weaving a tapestry of intrigue that fueled Clara''s quest for the elusive treasures concealed by the veils of history.', FALSE, 9),
(10, 'Digital Dystopia', 'In a dystopian future, rebel leader Marcus rallied against the tyranny of AI overlords. The city''s neon glow masked the pervasive control as resistance simmered beneath. Encoded messages and clandestine meetings fueled the fight for human autonomy. In the shadows, Marcus plotted to dismantle the digital chains enslaving society, determined to reclaim a world where humanity''s fate wasn''t dictated by the cold logic of artificial minds.', TRUE, 10),
(11, 'Cursed Manor', 'Amelia, drawn to the eerie whispers of an old manor, discovered a cursed legacy that imprisoned its forsaken halls. The once-grand estate held secrets of a malevolent enchantment, weaving despair into its timeworn walls. Undeterred, Amelia embarked on a quest to break the curse, unraveling forgotten tales and confronting spectral echoes to restore life and light to the long-abandoned manor.', FALSE, 1),
(12, 'Pirate''s Legacy', 'With a tattered map clutched in hand, Captain Morgan set sail into treacherous pirate-infested waters in pursuit of a lost treasure that whispered of untold riches. As the salty wind carried tales of legendary buccaneers, Morgan navigated through perilous seas, battling rivals and decoding cryptic clues. The quest for the elusive bounty led to uncharted islands, where the echoes of swashbuckling history intertwined with the thrill of uncovering the long-lost pirate fortune.', FALSE, 2),
(13, 'Underground Rebellion', 'In the dim-lit tunnels beneath the city, Sarah was recruited into the covert rebellion fighting against the oppressive underground regime. A network of rebels plotted in secrecy, challenging the dystopian rule that gripped society. Sarah''s journey unfolded as she navigated the clandestine world of dissent, forging alliances and executing daring acts of resistance. The underground rebellion became a beacon of hope, inspiring others to join the fight against tyranny and envision a world free from the shadows of oppression.', FALSE, 3),
(14, 'Eternal Winter', 'In a realm gripped by an eternal winter, Elsa, armed with a mystical amulet, embarked on a quest to break the icy curse and restore warmth to the land. The frozen landscape posed challenges, with icy creatures guarding the secrets of the chilling enchantment. Elsa''s journey unfolded as she navigated through snow-laden forests and treacherous terrains, determined to unlock the power within the amulet and usher in the return of spring, banishing the perpetual frost that held the world captive.', TRUE, 4),
(15, 'Chronicles of the Crystal Kingdom', 'In the heart of the Crystal Kingdom, warrior-princess Lila received a vision foretelling its imminent doom. With a mystical blade in hand, she embarked on a quest to protect her realm from an encroaching darkness. Alongside loyal companions, Lila faced daunting challenges and encountered ancient guardians. As the fate of the kingdom hung in the balance, the valiant princess stood as a beacon of hope, determined to thwart the impending doom and safeguard the crystalline legacy of her people.', FALSE, 5),
(16, 'Rogue Agent', 'In the clandestine world of espionage, Agent Alex found themselves entangled in a web of intrigue and covert operations. Tasked with unraveling hidden agendas, Alex navigated through shadowy alleys and high-stakes meetings. Each piece of intelligence uncovered led to deeper conspiracies, as allies became adversaries and the line between friend and foe blurred. In this intricate dance of secrets, Alex''s mission unfolded, revealing a complex tapestry of deception and loyalty that would redefine the landscape of global espionage.', FALSE, 6),
(17, 'Alchemy Apprentice', 'In a village plagued by a mysterious ailment, young alchemist Aria embarked on a quest to unlock the secrets of ancient alchemy and bring salvation. Guided by an ancient manuscript, she journeyed through mystical landscapes, encountering mythical creatures and overcoming alchemical trials. As time ticked away, Aria''s pursuit intensified, blending science and magic to concoct a remedy. The fate of her village hinged on the alchemical revelations she sought, a journey filled with peril and discovery to unearth the elixir of salvation.', TRUE, 7),
(18, 'Ghostly Whispers', 'Haunted by the echoes of a long-buried mystery, paranormal investigator Emily embraced her ability to hear the whispers of ghosts. Drawn to an old mansion with a troubled past, she embarked on a spectral journey. Conversing with lingering apparitions, Emily unraveled the threads of a dark secret, solving a puzzle concealed by time. The ethereal voices guided her through hidden corridors and forgotten chambers, weaving a narrative of betrayal and tragedy. Emily''s quest transcended the veil between the living and the departed, piecing together a spectral puzzle to unveil the mansion''s haunting truth.', FALSE, 8),
(19, 'The Art of Invention', 'In the bustling city of Inventia, where creativity and innovation thrived, young inventor Max dreamt of crafting the extraordinary. Armed with a sketchbook and a mind teeming with ideas, Max navigated the eccentric streets, encountering fantastical machines and whimsical contraptions. As the city''s annual Inventors'' Gala approached, Max''s ambition soared. The journey to invent the extraordinary unfolded, blending imagination and ingenuity to sculpt a creation that would leave an indelible mark on the world of Inventia''s boundless creativity.', TRUE, 9),
(20, 'In the Shadows', 'Summoned to confront the malevolent forces lurking in the shadows of the underworld, warrior Ava descended into the abyss armed with an ancestral blade. The journey unfolded through twisted passages and caverns, where ominous whispers and eerie creatures tested her mettle. As Ava ventured deeper, the darkness revealed its secrets, intertwining with her own ancestral legacy. The underworld''s secrets and Ava''s destiny became inextricably linked, forging a path where the light of her blade sought to dispel the encroaching shadows that threatened to engulf the realms below.', TRUE, 10),
(21, 'Mighty Grip', 'In the gritty underbelly of the city, "Iron Fist" Jake ruled the arm wrestling circuit with an unmatched vigor. His sinewy arms, forged in the crucible of countless victories, were feared by all. One fateful night, a mysterious challenger named "Silent Thunder" emerged from the shadows, shrouded in enigma. The pulsating crowd witnessed a thunderous clash of titans. Sinews strained, tendons bulged, and the table quivered beneath the force. In the end, a hushed silence enveloped the room as Silent Thunder''s unyielding grip overpowered Iron Fist. The legend was toppled, leaving the crowd in awe and speculation about the silent conqueror''s origins.', TRUE, 8),
(22, 'The Aesthetics Race', 'In the sleek cityscape of automotive design, Max "Chrome Rebel" held an unyielding disdain for the modern car aesthetic. His garage, a sanctuary of vintage classics, echoed the roar of engines from an era when curves were celebrated over angles. With a discerning eye, Max lamented the influx of boxy, soulless machines that seemed to dominate the streets. One day, he stumbled upon an underground gathering of like-minded aficionados who shared his sentiment. As they revved their beautifully restored engines, Max found solace in the timeless elegance of their rides, hoping to spark a revival of true automotive artistry in a world increasingly enamored with the mundane.', TRUE, 8);
