INSERT INTO submissions(id, content, votes, active, accepted, users_id, stories_id)
  VALUES (1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 10, TRUE, FALSE, 1, 1),
(2, 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 5, TRUE, TRUE, 2, 2),
(3, 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 8, TRUE, TRUE, 3, 3),
(4, 'Suspendisse potenti. Fusce tincidunt nulla sed libero luctus, id commodo est aliquam.', 12, TRUE, FALSE, 4, 4),
(5, 'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.', 7, TRUE, TRUE, 5, 5),
(6, 'Quisque eget libero vitae leo dapibus condimentum. Aliquam erat volutpat.', 15, TRUE, FALSE, 6, 6),
(7, 'Vivamus fringilla justo eget justo vulputate, eu volutpat velit cursus.', 9, TRUE, FALSE, 7, 7),
(8, 'Nam bibendum velit in nunc aliquam, nec venenatis metus congue.', 11, TRUE, FALSE, 8, 8),
(9, 'Integer in justo vitae augue tincidunt malesuada. Cras ac purus in justo cursus tincidunt id ut urna.', 13, TRUE, FALSE, 9, 9),
(10, 'Curabitur in metus vel leo ultrices volutpat in nec odio. Aliquam non malesuada velit.', 6, TRUE, FALSE, 10, 10),
(11, 'Fusce hendrerit quam a leo bibendum, id luctus ligula consequat. Aenean eget efficitur nisl.', 8, TRUE, FALSE, 10, 11),
(12, 'Pellentesque euismod justo eu urna venenatis, eget volutpat arcu sagittis.', 14, TRUE, FALSE, 10, 12),
(13, 'Maecenas aliquet orci vel elit varius, vel congue nisi consequat. Fusce malesuada purus eget ullamcorper dapibus.', 7, TRUE, TRUE, 5, 13),
(14, 'Morbi lacinia justo nec libero dapibus, eu ultricies libero semper.', 10, TRUE, TRUE, 3, 14),
(15, 'Aenean ac dolor in velit malesuada cursus. Vivamus at velit ac elit ultrices feugiat in et metus.', 9, TRUE, TRUE, 2, 15),
(16, 'Praesent auctor lacus vel velit hendrerit, nec facilisis augue dignissim.', 12, TRUE, FALSE, 4, 16),
(17, 'Nullam vel nisl nec felis consectetur tristique vel id lectus.', 11, TRUE, FALSE, 4, 17),
  -- (18, 'Sed nec tellus vel justo rhoncus varius a id libero.', 8, TRUE, FALSE, 8, 18),
(19, 'Cras euismod lacus id odio fermentum, at elementum ipsum bibendum.', 13, TRUE, FALSE, 5, 19),
(20, 'Donec et libero eu sem ultrices tincidunt. Integer sit amet metus vitae elit fringilla tristique.', 7, TRUE, FALSE, 1, 20),
(21, 'Fusce aliquam est at mi cursus, eu tristique justo feugiat.', 10, TRUE, FALSE, 1, 20),
(22, 'Vivamus blandit nulla at orci commodo, vel dapibus odio tristique.', 14, TRUE, FALSE, 2, 2),
(23, 'Quisque malesuada turpis vel dui efficitur, id consequat elit facilisis.', 9, TRUE, FALSE, 1, 2),
(24, 'Pellentesque sit amet ligula vel tortor tincidunt vestibulum. Quisque consectetur justo vitae tristique sollicitudin.', 11, TRUE, TRUE, 3, 4),
(25, 'Curabitur ac dolor in felis tristique sollicitudin non a lacus.', 8, TRUE, FALSE, 5, 5),
(26, 'Integer nec turpis id elit volutpat efficitur. Sed gravida purus vitae sapien iaculis vehicula.', 12, TRUE, TRUE, 6, 2),
(27, 'Maecenas auctor justo in ante gravida, in volutpat nisl vulputate.', 7, TRUE, FALSE, 7, 7),
  -- (28, 'Vestibulum malesuada risus ac sem luctus, in iaculis libero ultricies.', 9, TRUE, TRUE, 7, 18),
(29, 'Fusce tristique turpis a malesuada tempus. Vivamus suscipit neque in odio cursus, id feugiat tortor semper.', 6, TRUE, FALSE, 6, 19),
(30, 'Integer id ligula euismod, cursus ligula nec, aliquet urna. Sed eget mauris a ex venenatis tincidunt.', 11, TRUE, FALSE, 1, 10),
(31, 'Integer id ligula euismod, cursus ligula nec, aliquet urna. Sed eget mauris a ex venenatis tincidunt.', 21, TRUE, TRUE, 2, 2),
(32, 'Integer id ligula euismod, cursus ligula nec, aliquet urna. Sed eget mauris a ex venenatis tincidunt.', 6, TRUE, TRUE, 1, 2),
(33, 'Integer id ligula euismod, cursus ligula nec, aliquet urna. Sed eget mauris a ex venenatis tincidunt.', 0, TRUE, FALSE, 1, 2),
(34, 'Iursus ligula nec, aliquet urna. Sed eget mauris a ex venenatis tincidunt. Integer nec turpis id elit volutpat efficitur. Sed gravida purus vitae sapien iaculis vehicula.', 1, TRUE, FALSE, 1, 2),
(35, 'Iursus ligula nec, aliquet urna. Sed eget mauris a ex venenatis tincidunt. Integer nec turpis id elit volutpat efficitur. Sed gravida purus vitae sapien iaculis vehicula.', 3, TRUE, FALSE, 8, 4),
(36, 'Mauris a ex venenatis tincidunt. Integer nec turpis id elit volutpat efficitur. Sed gravida purus vitae sapien iaculis vehicula.', 11, TRUE, TRUE, 6, 4),
(37, 'Iursus ligula nec, aliquet urna. Sed eget mauris a ex venenatis tincidunt. Integer nec turpis id elit volutpat efficitur. Sed gravida purus vitae sapien iaculis vehicula.', 4, TRUE, TRUE, 8, 18),
(38, 'Iuriquet urna. Sed eget mauris a ex venenatis tincidunt. Integer nec turpis id elit volutpat efficitur. Sed gravida purus vitae sapien iaculis vehicula.', 1, TRUE, FALSE, 9, 18),
(39, 'Iuriquet urna. Sed eget mauris a ex venenatis tincidunt. Integer nec turpis id elit volutpat efficitur. Sed gravida purus vitae sapien iaculis vehicula.', 1, TRUE, TRUE, 9, 20),
(40, 'Sed gravida purus vitae sapien iaculis. Iux venenatis tincidunt. Integer nec turpis id elit volutpat efficitur. Sed gravida purus vitae sapien iaculis vehicula.', 1, TRUE, TRUE, 4, 20),
(41, 'Sed gravida purus vitae sapien iaculis vehicula.', 1, TRUE, TRUE, 1, 20),
(42, 'ursus ligula nec, aliquet urna. Sed eget mauris a ex venenatis tincidunt. Integer nec turpis. Sed gravida purus vitae sapien iaculis vehicula.', 1, TRUE, TRUE, 3, 18),
(43, 'Aliquet urna. Sed eget mauris a ex venenatis tincidunt. Integer nec turpis eget mauris a ex. Sed gravida purus vitae sapien iaculis vehicula. Mauris a ex venenatis tincidunt. Integer nec turpis id elit volutpat efficitur. Sed gravida purus vitae sapien iaculis vehicula.', 1, TRUE, TRUE, 7, 18),
(44, 'Palravida purus vitae sapien iaculis vehicula. Mauris a ex venenatis tincidunt. Integer nec turpis id elit volutpat efficitur.', 1, TRUE, TRUE, 2, 18),
(45, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 1, TRUE, FALSE, 4, 18),
(46, 'Labore et dolore magna aliqua. Egestas congue quisque egestas diam in arcu cursus euismod. Tortor at auctor urna nunc. Arcu risus quis varius quam quisque id diam. Et tortor consequat id porta nibh venenatis cras sed. Habitasse platea dictumst vestibulum rhoncus est pellentesque. Urna et pharetra pharetra massa massa ultricies mi. Id nibh tortor id aliquet lectus proin.', 1, TRUE, FALSE, 9, 18),
(47, 'Tortor at auctor urna nunc. Tincidunt ornare massa eget egestas. Vitae aliquet nec ullamcorper sit amet risus nullam eget. Suspendisse in est ante in nibh mauris cursus mattis. Habitasse platea dictumst vestibulum rhoncus est pellentesque. Urna et pharetra pharetra massa massa ultricies mi. Id nibh tortor id aliquet lectus proin.', 4, TRUE, FALSE, 2, 18),
(48, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 1, TRUE, TRUE, 4, 16),
(49, 'Tortor at auctor urna nunc. Arcu risus quis varius quam quisque id diam. Et tortor consequat id porta nibh venenatis cras sed. Habitasse platea dictumst vestibulum rhoncus est pellentesque.', 1, TRUE, TRUE, 9, 16),
(50, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 2, TRUE, TRUE, 3, 16),
(51, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 5, TRUE, FALSE, 5, 16),
(52, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 5, TRUE, FALSE, 3, 15),
(53, 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 2, TRUE, FALSE, 9, 15),
(54, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 5, TRUE, FALSE, 5, 12),
(55, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tepor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, qus nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 5, TRUE, FALSE, 3, 12),
(56, 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 2, TRUE, FALSE, 9, 12),
(57, 'Sincididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 2, TRUE, TRUE, 9, 12),
(58, 'Sincididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 2, TRUE, TRUE, 9, 11),
(59, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Sincididunt ut labore et dolore magna aliqua.', 2, TRUE, TRUE, 5, 11),
(60, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Sincididunt ut labore et dolore magna aliqua.', 3, TRUE, FALSE, 5, 11),
(61, 'Laliquip ex ea commodo consequat. Sincididunt ut labore et dolore magna aliqua.', 3, TRUE, FALSE, 10, 11),
(62, 'Sincididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 2, TRUE, TRUE, 9, 17),
(63, 'Sincididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 2, TRUE, TRUE, 9, 17),
(64, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Sincididunt ut labore et dolore magna aliqua.', 2, TRUE, TRUE, 5, 17),
(65, 'Sincididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 2, TRUE, TRUE, 2, 7),
(66, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Sincididunt ut labore et dolore magna aliqua.', 2, TRUE, TRUE, 8, 7),
(67, 'Sincididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 2, TRUE, TRUE, 9, 3),
(68, 'Sincididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 2, TRUE, TRUE, 1, 3),
(69, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Sincididunt ut labore et dolore magna aliqua.', 2, TRUE, TRUE, 5, 3),
(70, 'Sincididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 2, TRUE, TRUE, 2, 3),
(71, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Sincididunt ut labore et dolore magna aliqua.', 2, TRUE, TRUE, 8, 3),
(72, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Sincididunt ut labore et dolore magna aliqua.', 2, TRUE, TRUE, 5, 21),
(73, 'Sincididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 2, TRUE, TRUE, 2, 21),
(74, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Sincididunt ut labore et dolore magna aliqua.', 2, TRUE, TRUE, 8, 21),
(75, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Sincididunt ut labore et dolore magna aliqua.', 2, TRUE, TRUE, 8, 22),
(76, 'Sincididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 2, TRUE, TRUE, 9, 22),
(78, 'Sincididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 2, TRUE, TRUE, 1, 22),
(79, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Sincididunt ut labore et dolore magna aliqua.', 2, TRUE, TRUE, 5, 22),
(80, 'Sincididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut enim ad minim veniam, quis nostrud exercitati22n ullamco laboris nisi ut aliquip ex ea commodo consequat.', 2, TRUE, TRUE, 2, 3),
(81, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Sincididunt ut labore et dolore magna aliqua.', 2, TRUE, TRUE, 8, 22),
(82, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Sincididunt ut labore et dolore magna aliqua.', 2, TRUE, TRUE, 5, 22),
(83, 'Sincididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 2, TRUE, TRUE, 2, 22),
(84, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Sincididunt ut labore et dolore magna aliqua.', 2, TRUE, TRUE, 8, 22);
